DROP TABLE IF EXISTS Batch
DROP TABLE IF EXISTS Warehouse
DROP TABLE IF EXISTS Pharmacy
DROP TABLE IF EXISTS Product

CREATE TABLE Product (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(128)
);

CREATE TABLE Pharmacy (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(128),
	Address NVARCHAR(256),
	PhoneNumber NVARCHAR(20)
);

CREATE TABLE Warehouse (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	PharmacyId INT,
	Name NVARCHAR(128),
	FOREIGN KEY (PharmacyId) REFERENCES Pharmacy(Id) ON DELETE CASCADE
);


CREATE TABLE Batch (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	ProductId INT,
	WarehouseId INT,
	Quantity INT,	
	FOREIGN KEY (ProductId) REFERENCES Product(Id) ON DELETE CASCADE,
	FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id) ON DELETE CASCADE
);
